name: restaurant
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  connectivity_plus: ^6.0.5
  hooks_riverpod: ^2.5.2
  json_annotation: ^4.9.0
  top_snackbar_flutter: ^3.1.0
  flutter_hooks: ^0.20.5
  http: ^1.2.2
  get_it: ^7.7.0
  figma_squircle: ^0.5.3
  smooth_corner: ^1.1.0
  freezed_annotation: ^2.4.4
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  flutter_keyboard_visibility: ^6.0.0
  loading_indicator: ^3.1.1
  dartz: ^0.10.1
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1
  iconly: ^1.0.1
  cloud_firestore: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/restaurants.json
