import 'package:freezed_annotation/freezed_annotation.dart'; // Import for Freezed package (used for immutable data classes)

part 'restaurant.freezed.dart'; // Import generated Freezed code
part 'restaurant.g.dart'; // Import generated JSON serialization code

// Define an immutable data class for Restaurant using Freezed
@freezed
class Restaurant with _$Restaurant {
  // Factory constructor to create a Restaurant instance
  factory Restaurant({
    required int id, // Required integer for the restaurant ID
    required String name, // Required string for the restaurant name
    required String cuisine, // Required string for the type of cuisine
  }) = _Restaurant; // Private constructor generated by Freezed

  // Factory method to create a Restaurant instance from JSON
  factory Restaurant.fromJson(Map<String, dynamic> json) =>
      _$RestaurantFromJson(json); // Generated method for JSON deserialization
}
